import html
import re
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.entities import UIContent


ROOT = Path(__file__).resolve().parents[3]
FRONTEND_SRC = ROOT / "frontend" / "src"
TEXT_RE = re.compile(r">([^<>{}\n][^<>{}]*)<|['\"]([^'\"]*[A-Za-z][^'\"]*)['\"]")
BACKEND_DEFAULTS = {
    "api.error.invalid_credentials": "Invalid credentials",
    "api.error.user_exists": "User already exists",
    "api.error.user_missing": "User not found",
    "api.error.mailbox_exists": "Mailbox already exists",
    "api.error.mailbox_missing": "Mailbox not found",
    "api.error.employee_exists": "Employee already exists",
    "api.error.employee_missing": "Employee not found",
    "api.error.email_missing": "Email not found",
    "api.error.graph_credentials_missing": "Microsoft Graph credentials are not configured",
    "api.error.graph_app_credentials_missing": "Microsoft Graph application credentials are not configured",
    "api.error.graph_client_id_required": "Azure Client ID is required",
    "api.error.graph_check_failed": "Graph check failed: {error}",
    "api.error.gmail_credentials_missing": "Google OAuth credentials are not configured",
    "api.error.gmail_mailbox_required": "Choose a Gmail mailbox to test",
    "api.error.gmail_not_connected": "Connect this Gmail mailbox before testing",
    "api.error.gmail_account_mismatch": "Connected Google account does not match the mailbox address",
    "api.error.gmail_check_failed": "Gmail check failed: {error}",
    "api.error.mail_credentials_missing": "Complete Microsoft or Gmail authentication for every active mailbox before synchronization",
    "api.error.microsoft_provider_required": "This mailbox is not a Microsoft mailbox",
    "api.error.gmail_provider_required": "This mailbox is not a Gmail mailbox",
    "api.error.sync_no_mailbox": "Add at least one active mailbox before synchronization",
    "api.error.smtp_missing": "SMTP is not configured",
    "api.error.report_period_invalid": "Invalid report period",
    "api.error.content_exists": "Content key already exists",
    "api.error.content_missing": "Content key not found",
    "oauth.failed.title": "OEIS Outlook connect failed",
    "oauth.expired.body": "Login expired. Start Connect Outlook again.",
    "oauth.refresh_token_missing": "Microsoft login did not return refresh token",
    "oauth.mailbox_removed.body": "Mailbox was removed.",
    "oauth.connected.title": "OEIS Outlook connected",
    "oauth.connected.body": "You can close this tab and click Sync.",
    "gmail.oauth.failed.title": "OEIS Gmail connect failed",
    "gmail.oauth.expired.body": "Login expired. Start Connect Gmail again.",
    "gmail.oauth.refresh_token_missing": "Google login did not return a refresh token",
    "gmail.oauth.account_mismatch": "Expected {expected}, but Google connected {actual}. Start again with the correct account.",
    "gmail.oauth.connected.title": "OEIS Gmail connected",
    "gmail.oauth.connected.body": "You can close this tab and click Sync.",
    "report.pdf.title": "OEIS Report",
    "report.pdf.heading": "OEIS {period} Report - {dimension}",
    "report.unassigned": "Unassigned",
    "graph.group.allowed_mailboxes": "OEIS Allowed Mailboxes",
    "graph.permission.required": "Microsoft Graph application permission Mail.Read with admin consent",
    "graph.setup.accounts": "Accounts in any organizational directory and personal Microsoft accounts",
    "graph.script.requires_azure_cli": "# Requires Azure CLI and tenant admin permission",
    "graph.script.app_display_name": "OEIS Mailbox Monitor",
    "graph.script.secret_display_name": "oeis-local",
    "graph.exchange.description": "Restrict OEIS Graph access",
    "gmail.permission.required": "Gmail API read-only access",
    "notification.escalation.title": "{role} escalation",
    "notification.escalation.body": "<p><b>{subject}</b> from {sender} has been pending {hours:.1f} business hours.</p><p><a href='{url}'>Open dashboard</a></p>",
    "notification.escalation.subject": "OEIS escalation: {subject}",
    "notification.summary.greeting": "Good Evening {name}",
    "notification.summary.subject": "OEIS daily summary",
    "notification.summary.body": "<h2>{greeting}</h2><p>Pending Emails: {pending}<br>Critical: {critical}<br>Overdue: {overdue}<br>Average Reply Time: {average}</p><h3>Top Pending</h3><ul>{top}</ul><p><a href='{url}'>Click here for Dashboard</a></p>",
}
FRONTEND_DEFAULTS = {
    "boot.loading": "Loading OEIS...",
    "brand.name": "OEIS",
    "brand.full_name": "OFFICE EMAIL INTELLIGENCE",
    "brand.aria": "OEIS brand",
    "login.intro_aria": "OEIS product introduction",
    "login.kicker": "COMMUNICATION CONTROL, WITHOUT THE CHASE",
    "login.headline.line1": "Every customer email.",
    "login.headline.line2": "Visible. Timed. Accountable.",
    "login.summary": "OEIS turns Microsoft 365 and Gmail activity into a clear management view of pending replies, SLA exposure and team response.",
    "login.signal.title": "Live mailbox signal",
    "login.signal.detail": "Five-minute delta intelligence",
    "login.critical.value": "24h",
    "login.critical.label": "Critical escalation",
    "login.time.value": "UTC",
    "login.time.label": "Business-time aware",
    "login.trust.graph": "Microsoft Graph and Gmail API",
    "login.trust.password": "No mailbox password stored",
    "login.panel_aria": "Sign in",
    "login.eyebrow": "SECURE MANAGEMENT ACCESS",
    "login.title": "Welcome back",
    "login.description": "Sign in to review mailbox health, customer response risk and management reports.",
    "login.email": "Email",
    "login.password": "Password",
    "login.hide_password": "Hide password",
    "login.show_password": "Show password",
    "login.signing_in": "Signing in...",
    "login.submit": "Enter OEIS",
    "login.security.title": "Protected management session",
    "login.security.detail": "JWT access control - role-aware workspace",
    "login.footer": "Office Email Intelligence System - Production control",
    "nav.dashboard.name": "Dashboard",
    "nav.dashboard.description": "Executive overview",
    "nav.pending.name": "Pending Emails",
    "nav.pending.description": "Prioritized action queue",
    "nav.performance.name": "Employee Performance",
    "nav.performance.description": "Team response metrics",
    "nav.reports.name": "Reports",
    "nav.reports.description": "Trends, PDF & Excel",
    "nav.mailboxes.name": "Mailboxes",
    "nav.mailboxes.description": "Microsoft 365 and Gmail scope",
    "nav.escalations.name": "Escalations",
    "nav.escalations.description": "Threshold notifications",
    "nav.audit.name": "Audit Logs",
    "nav.audit.description": "Synchronization evidence",
    "nav.users.name": "Users & Roles",
    "nav.users.description": "Access and permissions",
    "nav.settings.name": "Settings",
    "nav.settings.description": "SLA and decision policy",
    "page.dashboard.eyebrow": "EXECUTIVE COMMAND CENTER",
    "page.dashboard.description": "Live communication risk, team response and integration confidence in one view.",
    "page.pending.eyebrow": "CUSTOMER ACTION QUEUE",
    "page.pending.description": "Prioritize unanswered customer conversations by SLA exposure and ownership.",
    "page.performance.eyebrow": "TEAM RESPONSE INTELLIGENCE",
    "page.performance.description": "Compare workload, response speed and resolution outcomes across coordinators.",
    "page.reports.eyebrow": "MANAGEMENT REPORTING",
    "page.reports.description": "Turn operational history into daily, weekly and monthly decision evidence.",
    "page.mailboxes.eyebrow": "MAILBOX COVERAGE",
    "page.mailboxes.description": "Control monitored Microsoft 365 and Gmail mailboxes, time zones and synchronization readiness.",
    "page.escalations.eyebrow": "ESCALATION GOVERNANCE",
    "page.escalations.description": "Review the Manager and Director alerts issued at SLA threshold crossings.",
    "page.audit.eyebrow": "OPERATIONAL EVIDENCE",
    "page.audit.description": "Trace every mailbox synchronization and escalation outcome.",
    "page.users.eyebrow": "SECURE ACCESS CONTROL",
    "page.users.description": "Manage the administrators and managers trusted with OEIS operations.",
    "page.settings.eyebrow": "DECISION POLICY",
    "page.settings.description": "Shape SLA thresholds, classification logic and business-time calendars without code.",
    "empty.default.title": "No records found",
    "empty.default.description": "This view will populate when OEIS has matching operational data.",
    "empty.pending.title": "No conversations match this view",
    "empty.pending.description": "Adjust the filters or wait for the next successful Microsoft 365 synchronization.",
    "empty.performance.title": "No active coordinator performance yet",
    "empty.performance.description": "Performance appears after employees are configured and customer replies are matched.",
    "empty.reports.title": "No report activity for this period",
    "empty.reports.description": "Choose another period or dimension, or synchronize mailboxes to begin building history.",
    "empty.mailboxes.title": "No monitored mailboxes",
    "empty.mailboxes.description": "Add a Microsoft 365 or Gmail mailbox to begin automatic SLA monitoring.",
    "empty.escalations.title": "No escalation events",
    "empty.escalations.description": "Manager and Director notifications will appear after configured SLA thresholds are crossed.",
    "empty.audit.title": "No automation evidence yet",
    "empty.audit.description": "Synchronization attempts and escalation deliveries will be recorded here automatically.",
    "empty.users.title": "No additional management users",
    "empty.users.description": "Create a Manager or Administrator account to delegate secure OEIS access.",
    "table.region_aria": "Operational records",
    "table.aria": "OEIS operational data",
    "table.actions": "Actions",
    "table.connect_outlook": "Connect Outlook",
    "table.connect_gmail": "Connect Gmail",
    "table.remove": "Remove",
    "status.active": "Active",
    "status.inactive": "Inactive",
    "kpi.today_emails.label": "Today's emails",
    "kpi.today_emails.note": "Received since midnight UTC",
    "kpi.pending_replies.label": "Pending replies",
    "kpi.pending_replies.note": "Customer emails awaiting action",
    "kpi.overdue.label": "Overdue",
    "kpi.overdue.note": "Beyond the red SLA threshold",
    "kpi.critical.label": "Critical",
    "kpi.critical.note": "Immediate management attention",
    "kpi.average_reply_hours.label": "Average reply time",
    "kpi.average_reply_hours.note": "Hours across resolved email",
    "kpi.resolved_today.label": "Resolved today",
    "kpi.resolved_today.note": "Replies completed today",
    "kpi.ignored_emails.label": "Ignored emails",
    "kpi.ignored_emails.note": "Excluded by classification rules",
    "graph_ui.empty": "Enter mailbox address to prepare Microsoft Graph setup.",
    "graph_ui.step.register.title": "Register OEIS app",
    "graph_ui.step.register.detail": "Create or open an Entra app registration.",
    "graph_ui.step.register.action": "Open app registration",
    "graph_ui.step.permission.title": "Grant Graph permission",
    "graph_ui.step.permission.personal.title": "Add delegated Graph permissions",
    "graph_ui.step.permission.personal.detail": "Add delegated Mail.Read and User.Read. OEIS requests offline_access during login.",
    "graph_ui.step.permission.action": "Open API permissions",
    "graph_ui.step.scope.title": "Limit mailbox scope",
    "graph_ui.step.scope.empty": "Mailbox address will fill Exchange command block.",
    "graph_ui.step.scope.action": "Open Exchange admin",
    "graph_ui.step.redirect.title": "Add the Web redirect URI",
    "graph_ui.step.redirect.detail": "Add http://localhost:8000/api/graph/oauth/callback under Authentication > Web.",
    "graph_ui.step.redirect.action": "Open app registration",
    "graph_ui.title": "Microsoft Graph setup pipeline",
    "graph_ui.configured": "Graph credentials detected. Complete mailbox access policy, then sync.",
    "graph_ui.personal_configured": "Graph credentials saved. Add the delegated permissions and redirect URI, then connect Outlook.",
    "graph_ui.missing": "Missing: {missing}",
    "graph_ui.none": "none",
    "graph_ui.info": "One click can open Microsoft setup pages. Tenant admin still must sign in and grant consent. Paste generated values here to save local backend `.env`.",
    "graph_ui.personal_info": "Personal Outlook uses delegated login. No Exchange mailbox policy or tenant admin consent is required.",
    "graph_ui.delegated": "Personal Outlook needs account type: {accounts}. Add Web redirect URI: {redirect}. Delegated scopes: {scopes}.",
    "graph_ui.start": "Start Microsoft setup",
    "graph_ui.ready": "Ready",
    "graph_ui.action": "Action",
    "graph_ui.admin_consent": "Open admin consent",
    "graph_ui.save_title": "Save Graph credentials",
    "graph_ui.tenant": "Tenant ID",
    "graph_ui.client": "Client ID",
    "graph_ui.secret": "Client secret (required for Outlook web login)",
    "graph_ui.scope": "Graph scope",
    "graph_ui.saving": "Saving...",
    "graph_ui.save": "Save credentials",
    "graph_ui.personal_note": "Personal Outlook: save Tenant ID + Client ID, add mailbox, then use Connect Outlook in Mailboxes. Test Graph uses app-only secret path.",
    "graph_ui.testing": "Testing...",
    "graph_ui.test": "Test app-secret Graph",
    "graph_ui.azure_title": "Azure CLI automation",
    "graph_ui.azure_copied": "Azure CLI script copied",
    "graph_ui.copy_azure": "Copy Azure CLI script",
    "graph_ui.download_script": "Download script",
    "graph_ui.env_title": "Environment values",
    "graph_ui.env_copied": ".env values copied",
    "graph_ui.copy_env": "Copy .env values",
    "graph_ui.download_env": "Download .env",
    "graph_ui.exchange_title": "Exchange mailbox policy",
    "graph_ui.exchange_copied": "Exchange commands copied",
    "graph_ui.copy_powershell": "Copy PowerShell",
    "graph_ui.download_powershell": "Download PowerShell",
    "gmail_ui.empty": "Choose Gmail to prepare Google OAuth setup.",
    "gmail_ui.title": "Gmail API setup pipeline",
    "gmail_ui.configured": "Google OAuth credentials detected. Add the mailbox, then connect its Google account.",
    "gmail_ui.missing": "Missing: {missing}",
    "gmail_ui.info": "Create a Google Cloud project, enable Gmail API, configure the OAuth consent screen, and create a Web application OAuth client.",
    "gmail_ui.step.project.title": "Create Google Cloud project",
    "gmail_ui.step.project.detail": "Create or select the project that will run OEIS.",
    "gmail_ui.step.project.action": "Open Google Cloud",
    "gmail_ui.step.api.title": "Enable Gmail API",
    "gmail_ui.step.api.action": "Open API library",
    "gmail_ui.step.consent.title": "Configure OAuth consent",
    "gmail_ui.step.consent.detail": "Add the mailbox as a test user while the app is in testing.",
    "gmail_ui.step.consent.action": "Open consent screen",
    "gmail_ui.step.credentials.title": "Create OAuth client",
    "gmail_ui.step.credentials.action": "Open credentials",
    "gmail_ui.required": "Required permission: {permission}",
    "gmail_ui.redirect": "Authorized redirect URI: {redirect}",
    "gmail_ui.scopes": "Scopes: {scopes}",
    "gmail_ui.start": "Start Google setup",
    "gmail_ui.ready": "Ready",
    "gmail_ui.action": "Action",
    "gmail_ui.save_title": "Save Google OAuth credentials",
    "gmail_ui.client": "Google client ID",
    "gmail_ui.secret": "Google client secret",
    "gmail_ui.saving": "Saving...",
    "gmail_ui.save": "Save credentials",
    "gmail_ui.env_title": "Environment values",
    "gmail_ui.env_copied": "Gmail .env values copied",
    "gmail_ui.copy_env": "Copy .env values",
    "gmail_ui.download_env": "Download .env",
    "shell.operations": "OPERATIONS",
    "shell.integration_operational": "Integration operational",
    "shell.integration_attention": "Integration needs attention",
    "shell.scheduler_configured": "Scheduler configured",
    "shell.last_sync": "Last sync {time}",
    "shell.delta_interval": "Five-minute delta interval",
    "shell.skip": "Skip to main content",
    "top.open_nav": "Open navigation",
    "top.product": "PRODUCTION OEIS",
    "top.scope": "Microsoft 365 + Gmail - Multi-mailbox",
    "top.guide": "Guide",
    "top.sign_out": "Sign out",
    "top.syncing": "Syncing...",
    "top.sync_now": "Sync now",
    "action.add_mailbox": "Add mailbox",
    "action.add_employee": "Add employee",
    "action.add_user": "Add user",
    "filter.search": "Search",
    "filter.status": "Status",
    "filter.date": "Date",
    "filter.mailbox": "Mailbox",
    "filter.employee": "Employee",
    "filter.pending": "Not Replied",
    "filter.critical": "Critical",
    "filter.overdue": "Overdue",
    "filter.replied": "Replied",
    "filter.any_date": "Any date",
    "filter.today": "Today",
    "filter.yesterday": "Yesterday",
    "filter.week": "This week",
    "filter.all_mailboxes": "All mailboxes",
    "filter.all_employees": "All employees",
    "filter.apply": "Apply",
    "filter.clear": "Clear",
    "report.period": "Period",
    "report.dimension": "Dimension",
    "report.daily": "Daily",
    "report.weekly": "Weekly",
    "report.monthly": "Monthly",
    "report.employee": "Employee-wise",
    "report.customer": "Customer-wise",
    "report.mailbox": "Mailbox-wise",
    "report.export_excel": "Export Excel",
    "report.export_pdf": "Export PDF",
    "report.send_daily": "Send daily summary now",
    "performance.sort_by": "Sort by",
    "performance.order": "Order",
    "performance.employee": "Employee",
    "performance.total": "Total replies",
    "performance.average": "Average reply time",
    "performance.pending": "Pending",
    "performance.critical": "Critical",
    "performance.resolved": "Resolved",
    "performance.ascending": "Ascending",
    "performance.descending": "Descending",
    "settings.tab.sla": "SLA rules",
    "settings.tab.classification": "Classification",
    "settings.tab.calendars": "Business calendars",
    "settings.tab.sync": "Synchronization",
    "settings.sync.title": "Mailbox synchronization",
    "settings.sync.description": "Choose how often OEIS checks connected mailboxes. Minimum is 10 seconds.",
    "settings.sync.interval": "Automatic sync interval (seconds)",
    "settings.sync.enabled": "Automatic synchronization",
    "settings.sync.helper": "Minimum 10 seconds. 60 seconds = 1 minute. 120 seconds = 2 minutes.",
    "settings.sync.save": "Save sync settings",
    "settings.sync.manual": "Run manual sync",
    "settings.sync.next": "Next automatic sync: {time}",
    "hint.matching": "{total} matching emails",
    "hint.mailboxes": "Click a mailbox row to edit its name, timezone, or synchronization status.",
    "hint.performance": "Click an employee row to update or deactivate the employee.",
    "hint.users": "Click a user row to change role, status, or password.",
    "hint.pending": "Click an email row to inspect identifiers, SLA details, and assignment.",
    "tour.count": "{current} of {total}",
    "tour.skip_product": "Skip product guide",
    "tour.progress": "Guide progress: step {current} of {total}",
    "tour.skip": "Skip guide",
    "tour.back": "Back",
    "tour.finish": "Finish",
    "tour.next": "Next",
    "tour.step.workspace.eyebrow": "WELCOME TO OEIS",
    "tour.step.workspace.title": "Your communication control room",
    "tour.step.workspace.description": "OEIS watches Microsoft 365 customer mailboxes automatically, identifies unanswered conversations, measures SLA time, and gives management one reliable operational view.",
    "tour.step.navigation.eyebrow": "WORKSPACE MAP",
    "tour.step.navigation.title": "Everything has a clear home",
    "tour.step.navigation.description": "Move from executive health to individual emails, team performance, reports, mailbox administration, audit evidence, and policy settings from this navigation.",
    "tour.step.readiness.eyebrow": "TRUST FIRST",
    "tour.step.readiness.title": "Know whether the data is current",
    "tour.step.readiness.description": "This posture panel separates real workload health from integration health. OEIS never presents failed or unsynchronized mailbox data as a healthy zero.",
    "tour.step.kpis.eyebrow": "EXECUTIVE PULSE",
    "tour.step.kpis.title": "Seven numbers answer the morning questions",
    "tour.step.kpis.description": "See today's intake, pending replies, overdue and critical risk, average reply time, today's resolutions, and correctly ignored automation at a glance.",
    "tour.step.sync.eyebrow": "DATA CONTROL",
    "tour.step.sync.title": "Synchronize on demand",
    "tour.step.sync.description": "The scheduler runs automatically at the interval configured in Settings. Administrators can request an immediate synchronization here.",
    "tour.step.pending.eyebrow": "ACTION QUEUE",
    "tour.step.pending.title": "Find every conversation needing attention",
    "tour.step.pending.description": "Search and combine status, date, mailbox, and employee filters. Open a row to inspect identifiers, business-hour SLA age, classification, and assignment.",
    "tour.step.performance.eyebrow": "TEAM VISIBILITY",
    "tour.step.performance.title": "Understand response performance",
    "tour.step.performance.description": "Compare replies, average response time, pending work, critical exposure, and resolved volume for each active support coordinator.",
    "tour.step.reports.eyebrow": "MANAGEMENT REPORTING",
    "tour.step.reports.title": "Move from live operations to trends",
    "tour.step.reports.description": "Switch daily, weekly, and monthly views by employee, customer, or mailbox; then export the evidence to Excel or PDF.",
    "tour.step.mailboxes.eyebrow": "MAILBOX PROVIDER SCOPE",
    "tour.step.mailboxes.title": "Control which mailboxes OEIS monitors",
    "tour.step.mailboxes.description": "Administrators add Microsoft 365 or Gmail mailboxes, connect them securely with OAuth, set time zones, pause synchronization, and inspect the last provider error without storing mailbox passwords.",
    "tour.step.escalations.eyebrow": "MANAGEMENT ATTENTION",
    "tour.step.escalations.title": "Escalate once, at the right threshold",
    "tour.step.escalations.description": "Review Manager and Director alerts generated when pending business time crosses configured thresholds. Unique event records prevent repeated alerts every five minutes.",
    "tour.step.audit.eyebrow": "ACCOUNTABILITY",
    "tour.step.audit.title": "Every automated action leaves evidence",
    "tour.step.audit.description": "Audit Logs combines synchronization attempts and escalation events so management can verify what ran, when it ran, and whether it succeeded.",
    "tour.step.users.eyebrow": "SECURE DELEGATION",
    "tour.step.users.title": "Give management the right level of access",
    "tour.step.users.description": "Administrators create Manager or Admin accounts, change roles, deactivate access, and rotate application login passwords without exposing mailbox credentials.",
    "tour.step.settings.eyebrow": "POLICY WITHOUT CODE",
    "tour.step.settings.title": "Configure how OEIS makes decisions",
    "tour.step.settings.description": "Edit SLA thresholds, escalation timing, ordered classification rules, working hours, weekends, holidays, and mailbox time zones through guided forms.",
    "tour.step.help.eyebrow": "YOU ARE READY",
    "tour.step.help.title": "Replay this guide whenever you need it",
    "tour.step.help.description": "Select Guide in the top bar at any time. The interface, status language, and empty states remain useful even after the tour is complete.",
    "dashboard.live_aria": "Live OEIS dashboard",
    "dashboard.integration.checking.message": "Checking Microsoft 365 and Gmail integrations",
    "dashboard.integration.checking.label": "Checking",
    "dashboard.integration.graph_missing.message": "Mailbox provider authentication is not complete",
    "dashboard.integration.graph_missing.label": "Not configured",
    "dashboard.integration.mailbox_missing.message": "No active Microsoft 365 or Gmail mailbox is configured",
    "dashboard.integration.mailbox_missing.label": "Setup required",
    "dashboard.integration.sync_failed.message": "Mailbox synchronization failed - dashboard data is not current",
    "dashboard.integration.first_sync.message": "Waiting for the first successful mailbox synchronization",
    "dashboard.integration.first_sync.label": "Not synchronized",
    "dashboard.integration.critical.message": "Critical customer communication requires attention",
    "dashboard.integration.overdue.message": "Customer communication SLA risk detected",
    "dashboard.integration.healthy.message": "Customer communication is under control",
    "dashboard.integration.healthy.label": "Healthy",
    "dashboard.posture": "OPERATIONAL POSTURE",
    "dashboard.live_posture": "LIVE POSTURE",
    "dashboard.last_success": "Last successful sync: {time}",
    "dashboard.as_of": "AS OF {time}",
    "dashboard.mailbox_error": "{count} mailbox error",
    "dashboard.critical_count": "{count} critical",
    "dashboard.overdue_count": "{count} overdue",
    "dashboard.metric_fallback": "Live repository metric",
    "dashboard.chart_sla_index": "01 / SLA",
    "dashboard.chart_sla_title": "Workload by response state",
    "dashboard.chart_sla_description": "Pending, overdue, critical and resolved today",
    "dashboard.chart_sla_aria": "SLA workload bar chart",
    "dashboard.chart_attention_index": "02 / ATTENTION",
    "dashboard.chart_attention_title": "Management focus",
    "dashboard.chart_attention_description": "Current SLA exposure distribution",
    "dashboard.chart_attention_aria": "Attention mix doughnut chart",
    "dashboard.within_sla": "Within SLA",
    "dashboard.emails": "Emails",
    "dashboard.analytics": "COMMUNICATION ANALYTICS",
    "dashboard.analytics_title": "Seven-signal workload",
    "dashboard.live_repository": "Live repository",
    "dashboard.analytics_aria": "Seven operational email metrics",
    "dashboard.next_move": "NEXT MANAGEMENT MOVE",
    "dashboard.resolve_critical": "Resolve critical exposure",
    "dashboard.clear_overdue": "Clear overdue replies",
    "dashboard.verify_flow": "Verify mailbox flow",
    "dashboard.critical_sentence": "{count} conversations need immediate management attention.",
    "dashboard.overdue_sentence": "{count} replies have crossed their SLA threshold.",
    "dashboard.verify_sentence": "Confirm a successful Microsoft 365 synchronization before relying on zero values.",
    "dashboard.open_queue": "Open queue",
    "dashboard.review_setup": "Review setup",
    "dashboard.attention_queue": "ATTENTION QUEUE",
    "dashboard.needs_decision": "What needs a decision",
    "dashboard.view_all": "View all",
    "dashboard.no_current_items": "No current items",
    "dashboard.active_items": "{count} active item{suffix}",
    "dashboard.control_chain": "CONTROL CHAIN",
    "dashboard.operational_readiness": "Operational readiness",
    "dashboard.ready_count": "{count}/4 ready",
    "dashboard.ready": "Ready",
    "dashboard.pending": "Pending",
    "dashboard.blocked": "Blocked",
    "dashboard.system_progress": "SYSTEM PROGRESS",
    "dashboard.intelligence_online": "Intelligence online",
    "dashboard.controls_ready": "controls ready",
    "dashboard.mailbox_pulse": "MAILBOX PULSE",
    "dashboard.last_verified_sync": "Last verified sync",
    "dashboard.awaiting_verified_sync": "Awaiting verified sync",
    "dashboard.view_evidence": "View evidence",
    "settings.invalid": "Settings data is not valid. Reload this section before editing.",
    "settings.sla.title": "Service-level policy",
    "settings.sla.description": "Control response thresholds and escalation timing.",
    "settings.classification.title": "Email classification",
    "settings.classification.description": "Rules run in priority order; unmatched messages become Customer emails.",
    "settings.calendars.title": "Business calendars",
    "settings.calendars.description": "Define working time used for SLA calculations.",
    "settings.add_rule": "Add rule",
    "settings.add_calendar": "Add calendar",
    "settings.business_hours": "Business hours only",
    "settings.threshold": "Tier begins at (hours)",
    "settings.notify_manager": "Notify Manager at",
    "settings.notify_director": "Notify Director at",
    "settings.rule_title": "Rule {number}",
    "settings.delete_rule": "Delete rule {number}",
    "settings.rule_name": "Rule name",
    "settings.priority": "Priority",
    "settings.match_field": "Match field",
    "settings.sender": "Sender",
    "settings.domain": "Domain",
    "settings.subject": "Subject",
    "settings.classification": "Classification",
    "settings.regex": "Regular expression",
    "settings.regex_help": "Case-insensitive regex; invalid patterns are rejected when saved.",
    "settings.mailbox_calendar": "Mailbox calendar #{id}",
    "settings.organization_default": "Organization default",
    "settings.delete_calendar": "Delete calendar {number}",
    "settings.timezone": "IANA timezone",
    "settings.workday_start": "Workday starts",
    "settings.workday_end": "Workday ends",
    "settings.weekdays": "Weekdays (0=Mon)",
    "settings.holidays": "Holidays (YYYY-MM-DD)",
    "settings.save": "Save settings",
    "settings.validation_note": "Changes are validated by the API before they are applied.",
    "dialog.cancel": "Cancel",
    "dialog.save_changes": "Save changes",
    "dialog.create": "Create",
    "dialog.edit": "Edit",
    "dialog.add": "Add",
    "dialog.mailbox.edit": "Edit mailbox",
    "dialog.mailbox.add": "Add mailbox",
    "dialog.mailbox.provider": "Email provider",
    "dialog.mailbox.microsoft": "Microsoft 365 / Outlook",
    "dialog.mailbox.gmail": "Google Gmail",
    "dialog.mailbox.address": "Address",
    "dialog.mailbox.display": "Display name",
    "dialog.mailbox.timezone": "Timezone",
    "dialog.mailbox.sync_status": "Synchronization status",
    "dialog.mailbox.paused": "Paused",
    "dialog.mailbox.error": "Error",
    "dialog.person.employee": "support employee",
    "dialog.person.user": "manager or administrator",
    "dialog.person.name": "Name",
    "dialog.person.email": "Email",
    "dialog.person.new_password": "New password (optional)",
    "dialog.person.temp_password": "Temporary password",
    "dialog.person.keep_password": "Leave blank to keep the current password",
    "dialog.person.min_password": "Minimum 12 characters",
    "dialog.person.role": "Role",
    "dialog.person.manager": "Manager",
    "dialog.person.admin": "Administrator",
    "dialog.person.active": "Active",
    "notice.graph_secret_saved": "Graph credentials saved. You can add mailbox and sync.",
    "notice.graph_client_saved": "Client ID saved. Add mailbox, then Connect Outlook.",
    "notice.graph_mailbox_verified": "Graph credentials and mailbox access verified.",
    "notice.graph_verified": "Graph credentials verified.",
    "notice.gmail_saved": "Google OAuth credentials saved. Add the mailbox, then Connect Gmail.",
    "notice.gmail_verified": "Gmail connection verified.",
    "notice.email_assignment_updated": "Email assignment updated.",
    "notice.mailbox_removed": "Mailbox removed.",
    "detail.close": "Close email details",
    "detail.email": "Email",
    "detail.sender": "SENDER",
    "detail.receiver": "RECEIVER",
    "detail.received": "RECEIVED",
    "detail.classification_status": "CLASSIFICATION / STATUS",
    "detail.pending_hours": "PENDING BUSINESS HOURS",
    "detail.internet_message_id": "INTERNET MESSAGE ID",
    "detail.conversation_id": "CONVERSATION ID",
    "detail.unavailable": "Unavailable",
    "detail.assigned_employee": "Assigned employee",
    "detail.assigned_employee_admin": "Assigned employee (Admin managed)",
    "detail.unassigned": "Unassigned",
}


def _frontend_strings() -> set[str]:
    values: set[str] = set()
    if not FRONTEND_SRC.exists():
        return values
    for path in FRONTEND_SRC.rglob("*"):
        if path.suffix not in {".tsx", ".ts", ".css"}:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        for jsx_text, literal in TEXT_RE.findall(text):
            value = html.unescape((jsx_text or literal).strip())
            if len(value) >= 2 and any(char.isalpha() for char in value):
                values.add(value)
    return values


def seed_ui_content(db: Session) -> int:
    existing_rows = {
        row.source_text: row
        for row in db.scalars(select(UIContent))
    }
    defaults = {**BACKEND_DEFAULTS, **FRONTEND_DEFAULTS}
    existing = set(existing_rows)
    pending: dict[str, str] = {value: value for value in sorted(_frontend_strings()) if value not in existing}
    pending.update({key: value for key, value in BACKEND_DEFAULTS.items() if key not in existing})
    pending.update({key: value for key, value in FRONTEND_DEFAULTS.items() if key not in existing})
    rows = [UIContent(source_text=key, rendered_text=value, active=True) for key, value in pending.items()]
    updated = 0
    for key, row in existing_rows.items():
        if row.rendered_text == key and key in defaults and defaults[key] != key:
            row.rendered_text = defaults[key]
            updated += 1
    pending_filter = existing_rows.get("filter.pending")
    if pending_filter and pending_filter.rendered_text == "Pending":
        pending_filter.rendered_text = FRONTEND_DEFAULTS["filter.pending"]
        updated = 1
    if not rows and not updated:
        return 0
    if rows:
        db.add_all(rows)
    db.commit()
    return len(rows) + updated


def content(db: Session, key: str, **values: object) -> str:
    row = db.scalar(select(UIContent).where(UIContent.source_text == key, UIContent.active.is_(True)))
    template = row.rendered_text if row else BACKEND_DEFAULTS.get(key, key)
    return template.format(**values) if values else template
